### ISSUE TITLE
Delete datasets as they are deleted on CKAN

### ISSUE THREAD

**Issue by rflprr** [datadotworld/ckanext-datadotworld#18]
Currently, the CKAN extension does not delete datasets on data.world once they are deleted on data.world. 

Instead, now that a DELETE endpoint has been released, the CKAN extension should properly delete them on data.world.

More info here: https://dwapi.api-docs.io/v0/datasets/delete-a-dataset

IMPORTANT: This endpoint requires a token with [admin permissions](https://data.world/settings/advanced). Existing users should be advised to obtain a token with such permission if DELETE requests fail with HTTP 403.

**Comment by iaroslav13** [comment]
@rflprr is there any information online about getting a token with "admin permissions"?

**Comment by rflprr** [comment]
@iaroslav13 They are available in https://data.world/settings/advanced now.
