### ISSUE TITLE
Normalize tags to satisfy data.world constraints

### ISSUE THREAD

**Issue by rflprr** [datadotworld/ckanext-datadotworld#21]
Currently, if tags on the CKAN side contain characters not allowed by data.world, datasets fail to sync.

Instead, the CKAN extension should normalize tags so that they only contain lower-case letters, numbers or spaces.

**Comment by rflprr** [comment]
Hi, @iaroslav13. Could you please prioritize this issue? This is currently a blocker for an important partner and I would like to get a hotfix in within the next couple of days, if possible.

**Comment by iaroslav13** [comment]
Hi @rflprr, we will fix it soon.
