### ISSUE TITLE
Fix file names and extensions

### ISSUE THREAD

**Issue by rflprr** [datadotworld/ckanext-datadotworld#3]
Currently, when I add a resource using:
- URL: https://www.ers.usda.gov/webdocs/DataFiles/51035/apples.xlsx?v=42082
- Name: Fruit and Vegetable Prices
- Type: **xlsx**

The file created on data.world has the wrong name: Fruit and Vegetable Prices.xlsx?v=42082

Instead, the name should be: **Fruit and Vegetable Prices.xlsx**

We need some heuristics to choose the right extension here:
1. If user provides file type, use the correct extension for the type
2. Otherwise, if user provides extension with the file name, use the name as provided
3. Otherwise, extract extension from URL (discarding query string completely)

**Comment by iaroslav13** [comment]
Fixed in #7
